// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderService.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SP.Service {

  /// <summary>Holder for reflection information generated from OrderService.proto</summary>
  public static partial class OrderServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for OrderService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OrderServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJPcmRlclNlcnZpY2UucHJvdG8SClNQLlNlcnZpY2UaEUNvbW1vbk1vZGVs",
            "LnByb3RvGhBPcmRlck1vZGVsLnByb3RvMtEHCgxPcmRlclNlcnZpY2USSQoK",
            "QWRkTXlPcmRlchIbLlNQLlNlcnZpY2UuQWRkT3JkZXJSZXF1ZXN0GhwuU1Au",
            "U2VydmljZS5BZGRPcmRlclJlc3BvbnNlIgASTQoOR2V0TXlPcmRlckxpc3QS",
            "Gi5TUC5TZXJ2aWNlLk15T3JkZXJSZXF1ZXN0Gh0uU1AuU2VydmljZS5PcmRl",
            "ckxpc3RSZXNwb25zZSIAElsKFlNlYXJjaE9yZGVyS2V5d29yZExpc3QSIC5T",
            "UC5TZXJ2aWNlLlNlYXJjaE15T3JkZXJSZXF1ZXN0Gh0uU1AuU2VydmljZS5P",
            "cmRlckxpc3RSZXNwb25zZSIAElYKFkdldE15T3JkZXJMaXN0QnlTdGF0dXMS",
            "Gy5TUC5TZXJ2aWNlLkdldE9yZGVyUmVxdWVzdBodLlNQLlNlcnZpY2UuT3Jk",
            "ZXJMaXN0UmVzcG9uc2UiABJMChFHZXRPcmRlckJ5T3JkZXJJZBIaLlNQLlNl",
            "cnZpY2UuT3JkZXJJZFJlcXVlc3QaGS5TUC5TZXJ2aWNlLk9yZGVyUmVzcG9u",
            "c2UiABJWChFVcGRhdGVPcmRlclN0YXR1cxIeLlNQLlNlcnZpY2UuVXBkYXRl",
            "T3JkZXJSZXF1ZXN0Gh8uU1AuU2VydmljZS5PcmRlclN0YXR1c1Jlc3BvbnNl",
            "IgASXQoRR2V0U2Nob29sTGVhZExpc3QSHS5TUC5TZXJ2aWNlLlNjaG9vbExl",
            "YWRSZXF1ZXN0GicuU1AuU2VydmljZS5TY2hvb2xMZWFkT3JkZXJMaXN0UmVz",
            "cG9uc2UiABJTChZHZXRTY2hvb2xMZWFkVHJhZGVMaXN0EhguU1AuU2Vydmlj",
            "ZS5UcmFkZVJlcXVlc3QaHS5TUC5TZXJ2aWNlLlRyYWRlTGlzdFJlc3BvbnNl",
            "IgASXQoUR2V0U2Nob29sTGVhZEZpbmFuY2USHC5TUC5TZXJ2aWNlLkFjY291",
            "bnRJZFJlcXVlc3QaJS5TUC5TZXJ2aWNlLlNjaG9vbExlYWRGaW5hbmNlUmVz",
            "cG9uc2UiABJSCgxBZGRDYXNoQXBwbHkSHy5TUC5TZXJ2aWNlLkFkZENhc2hB",
            "cHBseVJlcXVlc3QaHy5TUC5TZXJ2aWNlLk9yZGVyU3RhdHVzUmVzcG9uc2Ui",
            "ABJlChxVcGRhdGVPcmRlclN0YXR1c0J5T3JkZXJDb2RlEiIuU1AuU2Vydmlj",
            "ZS5VcGRhdGVPcmRlckNvZGVSZXF1ZXN0Gh8uU1AuU2VydmljZS5PcmRlclN0",
            "YXR1c1Jlc3BvbnNlIgBiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SP.Service.CommonModelReflection.Descriptor, global::SP.Service.OrderModelReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
