// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountService.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SP.Service {

  /// <summary>Holder for reflection information generated from AccountService.proto</summary>
  public static partial class AccountServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for AccountService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AccountServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRBY2NvdW50U2VydmljZS5wcm90bxIKU1AuU2VydmljZRoRQ29tbW9uTW9k",
            "ZWwucHJvdG8aEkFjY291bnRNb2RlbC5wcm90bzL/IAoOQWNjb3VudFNlcnZp",
            "Y2USTwoNUmVnaXN0QWNjb3VudBIZLlNQLlNlcnZpY2UuUmVnaXN0UmVxdWVz",
            "dBohLlNQLlNlcnZpY2UuQWNjb3VudFJlc3VsdFJlc3BvbnNlIgASVgoNVXBk",
            "YXRlQWNjb3VudBIgLlNQLlNlcnZpY2UuVXBkYXRlQWNjb3VudFJlcXVlc3Qa",
            "IS5TUC5TZXJ2aWNlLkFjY291bnRSZXN1bHRSZXNwb25zZSIAEk4KDVZhbGlk",
            "YXRlTG9naW4SGC5TUC5TZXJ2aWNlLkxvZ2luUmVxdWVzdBohLlNQLlNlcnZp",
            "Y2UuQWNjb3VudFJlc3VsdFJlc3BvbnNlIgASTwoQR2V0QWNjb3VudERldGFp",
            "bBIcLlNQLlNlcnZpY2UuQWNjb3VudElkUmVxdWVzdBobLlNQLlNlcnZpY2Uu",
            "QWNjb3VudFJlc3BvbnNlIgASRwoKR2V0QWNjb3VudBIaLlNQLlNlcnZpY2Uu",
            "QWNjb3VudFJlcXVlc3QaGy5TUC5TZXJ2aWNlLkFjY291bnRSZXNwb25zZSIA",
            "ElQKEUFkZEFjY291bnRBZGRyZXNzEhouU1AuU2VydmljZS5BZGRyZXNzUmVx",
            "dWVzdBohLlNQLlNlcnZpY2UuQWNjb3VudFJlc3VsdFJlc3BvbnNlIgASVQoS",
            "RWRpdEFjY291bnRBZGRyZXNzEhouU1AuU2VydmljZS5BZGRyZXNzUmVxdWVz",
            "dBohLlNQLlNlcnZpY2UuQWNjb3VudFJlc3VsdFJlc3BvbnNlIgASXAoTVXBk",
            "YXRlQWRkcmVzc1N0YXR1cxIgLlNQLlNlcnZpY2UuQWRkcmVzc1N0YXR1c1Jl",
            "cXVlc3QaIS5TUC5TZXJ2aWNlLkFjY291bnRSZXN1bHRSZXNwb25zZSIAElgK",
            "EVVwZGF0ZUFkZHJlc3NEb3JtEh4uU1AuU2VydmljZS5BZGRyZXNzRG9ybVJl",
            "cXVlc3QaIS5TUC5TZXJ2aWNlLkFjY291bnRSZXN1bHRSZXNwb25zZSIAElEK",
            "DkdldEFkZHJlc3NMaXN0EhwuU1AuU2VydmljZS5BY2NvdW50SWRSZXF1ZXN0",
            "Gh8uU1AuU2VydmljZS5BZGRyZXNzTGlzdFJlc3BvbnNlIgASUAoKRGVsQWRk",
            "cmVzcxIdLlNQLlNlcnZpY2UuRGVsQWRkcmVzc1JlcXVlc3QaIS5TUC5TZXJ2",
            "aWNlLkFjY291bnRSZXN1bHRSZXNwb25zZSIAElAKDkdldEFjY2Vzc1Rva2Vu",
            "EhsuU1AuU2VydmljZS5Ub2tlbktleVJlcXVlc3QaHy5TUC5TZXJ2aWNlLkFj",
            "Y2Vzc1Rva2VuUmVzcG9uc2UiABJeChxHZXRBY2Nlc3NUb2tlbkJ5UmVmcmVz",
            "aFRva2VuEhsuU1AuU2VydmljZS5Ub2tlbktleVJlcXVlc3QaHy5TUC5TZXJ2",
            "aWNlLkFjY2Vzc1Rva2VuUmVzcG9uc2UiABJTCg5BZGRBY2Nlc3NUb2tlbhIe",
            "LlNQLlNlcnZpY2UuQWNjZXNzVG9rZW5SZXF1ZXN0Gh8uU1AuU2VydmljZS5B",
            "Y2Nlc3NUb2tlblJlc3BvbnNlIgASUgoRUmVtb3ZlQWNjZXNzVG9rZW4SGi5T",
            "UC5TZXJ2aWNlLlRva2VuSWRSZXF1ZXN0Gh8uU1AuU2VydmljZS5BY2Nlc3NU",
            "b2tlblJlc3BvbnNlIgASVAoRR2V0UmVnaW9uRGF0YUxpc3QSHS5TUC5TZXJ2",
            "aWNlLlJlZ2lvbkRhdGFSZXF1ZXN0Gh4uU1AuU2VydmljZS5SZWdpb25MaXN0",
            "UmVzcG9uc2UiABJOCg1HZXRSZWdpb25EYXRhEhsuU1AuU2VydmljZS5SZWdp",
            "b25JRFJlcXVlc3QaHi5TUC5TZXJ2aWNlLlJlZ2lvbkRhdGFSZXNwb25zZSIA",
            "ElMKEkdldENoaWxkUmVnaW9uRGF0YRIbLlNQLlNlcnZpY2UuUmVnaW9uSURS",
            "ZXF1ZXN0Gh4uU1AuU2VydmljZS5SZWdpb25MaXN0UmVzcG9uc2UiABJcCg9B",
            "ZGRTaG9wcGluZ0NhcnQSHy5TUC5TZXJ2aWNlLlNob3BwaW5nQ2FydFJlcXVl",
            "c3QaJi5TUC5TZXJ2aWNlLlNob3BwaW5nQ2FydFJlc3VsdFJlc3BvbnNlIgAS",
            "XQoVR2V0TXlTaG9wcGluZ0NhcnRMaXN0EhwuU1AuU2VydmljZS5BY2NvdW50",
            "SWRSZXF1ZXN0GiQuU1AuU2VydmljZS5TaG9wcGluZ0NhcnRMaXN0UmVzcG9u",
            "c2UiABJrCh5HZXRNeVNob3BwaW5nQ2FydExpc3RCeU9yZGVySWQSIS5TUC5T",
            "ZXJ2aWNlLk15U2hvcHBpbmdDYXJ0UmVxdWVzdBokLlNQLlNlcnZpY2UuU2hv",
            "cHBpbmdDYXJ0TGlzdFJlc3BvbnNlIgASXwoWR2V0TXlTaG9wcGluZ0NhcnRD",
            "b3VudBIcLlNQLlNlcnZpY2UuQWNjb3VudElkUmVxdWVzdBolLlNQLlNlcnZp",
            "Y2UuU2hvcHBpbmdDYXJ0Q291bnRSZXNwb25zZSIAEm8KGlVwZGF0ZVNob3Bw",
            "aW5nQ2FydFF1YW50aXR5EicuU1AuU2VydmljZS5TaG9wcGluZ0NhcnRRdWFu",
            "dGl0eVJlcXVlc3QaJi5TUC5TZXJ2aWNlLlNob3BwaW5nQ2FydFJlc3VsdFJl",
            "c3BvbnNlIgASYwoZVXBkYXRlU2hvcHBpbmdDYXJ0RW5hYmxlZBIcLlNQLlNl",
            "cnZpY2UuQWNjb3VudElkUmVxdWVzdBomLlNQLlNlcnZpY2UuU2hvcHBpbmdD",
            "YXJ0UmVzdWx0UmVzcG9uc2UiABJtChlVcGRhdGVTaG9wcGluZ0NhcnRPcmRl",
            "cklkEiYuU1AuU2VydmljZS5TaG9wcGluZ0NhcnRPcmRlcklkUmVxdWVzdBom",
            "LlNQLlNlcnZpY2UuU2hvcHBpbmdDYXJ0UmVzdWx0UmVzcG9uc2UiABJbChlH",
            "ZXRTZWxlY3RlZFJlZ2lvbkRhdGFMaXN0EhwuU1AuU2VydmljZS5BY2NvdW50",
            "SWRSZXF1ZXN0Gh4uU1AuU2VydmljZS5SZWdpb25MaXN0UmVzcG9uc2UiABJY",
            "ChlHZXREZWZhdWx0U2VsZWN0ZWRBZGRyZXNzEhwuU1AuU2VydmljZS5BY2Nv",
            "dW50SWRSZXF1ZXN0GhsuU1AuU2VydmljZS5BZGRyZXNzUmVzcG9uc2UiABJX",
            "ChZHZXRDaGlsZFJlZ2lvbkRhdGFMaXN0EhsuU1AuU2VydmljZS5SZWdpb25J",
            "RFJlcXVlc3QaHi5TUC5TZXJ2aWNlLlJlZ2lvbkxpc3RSZXNwb25zZSIAEmUK",
            "GEFkZEFjY291bnRBdXRoZW50aWNhdGlvbhIkLlNQLlNlcnZpY2UuQWRkQXV0",
            "aGVudGljYXRpb25SZXF1ZXN0GiEuU1AuU2VydmljZS5BY2NvdW50UmVzdWx0",
            "UmVzcG9uc2UiABJhChtHZXRWYWxpZFZlcmlmeUNvZGVCeUFjY291bnQSIC5T",
            "UC5TZXJ2aWNlLkdldFZlcmlmeUNvZGVSZXF1ZXN0Gh4uU1AuU2VydmljZS5W",
            "ZXJpZnlDb2RlUmVzcG9uc2UiABJpChlVcGRhdGVBdXRoU3RhdHVzQnlBY2Nv",
            "dW50EicuU1AuU2VydmljZS5VcGRhdGVBdXRoZW50aWNhdGlvblJlcXVlc3Qa",
            "IS5TUC5TZXJ2aWNlLkFjY291bnRSZXN1bHRSZXNwb25zZSIAElMKDUFkZEFz",
            "c29jaWF0b3ISIC5TUC5TZXJ2aWNlLkFkZEFzc29jaWF0b3JSZXF1ZXN0Gh4u",
            "U1AuU2VydmljZS5Bc3NvY2lhdG9yUmVzcG9uc2UiABJoChZVcGRhdGVBc3Nv",
            "Y2lhdG9yU3RhdHVzEikuU1AuU2VydmljZS5VcGRhdGVBc3NvY2lhdG9yU3Rh",
            "dHVzUmVxdWVzdBohLlNQLlNlcnZpY2UuQWNjb3VudFJlc3VsdFJlc3BvbnNl",
            "IgASXgoYR2V0QXNzb2NpYXRvckJ5QWNjb3VudElkEhwuU1AuU2VydmljZS5B",
            "Y2NvdW50SWRSZXF1ZXN0GiIuU1AuU2VydmljZS5Bc3NvY2lhdG9yTGlzdFJl",
            "c3BvbnNlIgASVgoRR2V0QXNzb2NpYXRvckJ5SWQSHy5TUC5TZXJ2aWNlLkFz",
            "c29jaWF0b3JJZFJlcXVlc3QaHi5TUC5TZXJ2aWNlLkFzc29jaWF0b3JSZXNw",
            "b25zZSIAElIKDkdldFN5c0tpbmRMaXN0Eh0uU1AuU2VydmljZS5HZXRTeXNL",
            "aW5kUmVxdWVzdBofLlNQLlNlcnZpY2UuU3lzS2luZExpc3RSZXNwb25zZSIA",
            "ElkKEkdldEFjY291bnRGdWxsSW5mbxIcLlNQLlNlcnZpY2UuQWNjb3VudElk",
            "UmVxdWVzdBojLlNQLlNlcnZpY2UuQWNjb3VudEZ1bGxJbmZvUmVzcG9uc2Ui",
            "ABJgChVVcGRhdGVBY2NvdW50RnVsbEluZm8SIi5TUC5TZXJ2aWNlLkFjY291",
            "bnRGdWxsSW5mb1JlcXVlc3QaIS5TUC5TZXJ2aWNlLkFjY291bnRSZXN1bHRS",
            "ZXNwb25zZSIAElsKFkdldERpc2NvdW50QnlBY2NvdW50SWQSGy5TUC5TZXJ2",
            "aWNlLkRpc2NvdW50UmVxdWVzdBoiLlNQLlNlcnZpY2UuQXNzb2NpYXRvckxp",
            "c3RSZXNwb25zZSIAElkKEFNldEFjY291bnRQYXlQd2QSIC5TUC5TZXJ2aWNl",
            "LkFjY291bnRQYXlQd2RSZXF1ZXN0GiEuU1AuU2VydmljZS5BY2NvdW50UmVz",
            "dWx0UmVzcG9uc2UiABJcChNVcGRhdGVBY2NvdW50UGF5UHdkEiAuU1AuU2Vy",
            "dmljZS5BY2NvdW50UGF5UHdkUmVxdWVzdBohLlNQLlNlcnZpY2UuQWNjb3Vu",
            "dFJlc3VsdFJlc3BvbnNlIgASXgoVVXBkYXRlQWNjb3VudExvZ2luUHdkEiAu",
            "U1AuU2VydmljZS5BY2NvdW50UGF5UHdkUmVxdWVzdBohLlNQLlNlcnZpY2Uu",
            "QWNjb3VudFJlc3VsdFJlc3BvbnNlIgASXAoTVXBkYXRlQWNjb3VudE1vYmls",
            "ZRIgLlNQLlNlcnZpY2UuQWNjb3VudE1vYmlsZVJlcXVlc3QaIS5TUC5TZXJ2",
            "aWNlLkFjY291bnRSZXN1bHRSZXNwb25zZSIAElcKEEJpbmRPdGhlckFjY291",
            "bnQSHi5TUC5TZXJ2aWNlLkJpbmdBY2NvdW50UmVxdWVzdBohLlNQLlNlcnZp",
            "Y2UuQWNjb3VudFJlc3VsdFJlc3BvbnNlIgASWgoSQ3JlYXRlT3RoZXJBY2Nv",
            "dW50Eh8uU1AuU2VydmljZS5PdGhlckFjY291bnRSZXF1ZXN0GiEuU1AuU2Vy",
            "dmljZS5BY2NvdW50UmVzdWx0UmVzcG9uc2UiABJUCg9HZXRPdGhlckFjY291",
            "bnQSIi5TUC5TZXJ2aWNlLkdldE90aGVyQWNjb3VudFJlcXVlc3QaGy5TUC5T",
            "ZXJ2aWNlLkFjY291bnRSZXNwb25zZSIAYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SP.Service.CommonModelReflection.Descriptor, global::SP.Service.AccountModelReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
