// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountService.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SP.Service {

  /// <summary>Holder for reflection information generated from AccountService.proto</summary>
  public static partial class AccountServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for AccountService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AccountServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRBY2NvdW50U2VydmljZS5wcm90bxIKU1AuU2VydmljZRoRQ29tbW9uTW9k",
            "ZWwucHJvdG8aEkFjY291bnRNb2RlbC5wcm90bzLLGgoOQWNjb3VudFNlcnZp",
            "Y2USTwoNUmVnaXN0QWNjb3VudBIZLlNQLlNlcnZpY2UuUmVnaXN0UmVxdWVz",
            "dBohLlNQLlNlcnZpY2UuQWNjb3VudFJlc3VsdFJlc3BvbnNlIgASTgoNVmFs",
            "aWRhdGVMb2dpbhIYLlNQLlNlcnZpY2UuTG9naW5SZXF1ZXN0GiEuU1AuU2Vy",
            "dmljZS5BY2NvdW50UmVzdWx0UmVzcG9uc2UiABJPChBHZXRBY2NvdW50RGV0",
            "YWlsEhwuU1AuU2VydmljZS5BY2NvdW50SWRSZXF1ZXN0GhsuU1AuU2Vydmlj",
            "ZS5BY2NvdW50UmVzcG9uc2UiABJHCgpHZXRBY2NvdW50EhouU1AuU2Vydmlj",
            "ZS5BY2NvdW50UmVxdWVzdBobLlNQLlNlcnZpY2UuQWNjb3VudFJlc3BvbnNl",
            "IgASVAoRQWRkQWNjb3VudEFkZHJlc3MSGi5TUC5TZXJ2aWNlLkFkZHJlc3NS",
            "ZXF1ZXN0GiEuU1AuU2VydmljZS5BY2NvdW50UmVzdWx0UmVzcG9uc2UiABJV",
            "ChJFZGl0QWNjb3VudEFkZHJlc3MSGi5TUC5TZXJ2aWNlLkFkZHJlc3NSZXF1",
            "ZXN0GiEuU1AuU2VydmljZS5BY2NvdW50UmVzdWx0UmVzcG9uc2UiABJcChNV",
            "cGRhdGVBZGRyZXNzU3RhdHVzEiAuU1AuU2VydmljZS5BZGRyZXNzU3RhdHVz",
            "UmVxdWVzdBohLlNQLlNlcnZpY2UuQWNjb3VudFJlc3VsdFJlc3BvbnNlIgAS",
            "UQoOR2V0QWRkcmVzc0xpc3QSHC5TUC5TZXJ2aWNlLkFjY291bnRJZFJlcXVl",
            "c3QaHy5TUC5TZXJ2aWNlLkFkZHJlc3NMaXN0UmVzcG9uc2UiABJQCgpEZWxB",
            "ZGRyZXNzEh0uU1AuU2VydmljZS5EZWxBZGRyZXNzUmVxdWVzdBohLlNQLlNl",
            "cnZpY2UuQWNjb3VudFJlc3VsdFJlc3BvbnNlIgASUAoOR2V0QWNjZXNzVG9r",
            "ZW4SGy5TUC5TZXJ2aWNlLlRva2VuS2V5UmVxdWVzdBofLlNQLlNlcnZpY2Uu",
            "QWNjZXNzVG9rZW5SZXNwb25zZSIAEl4KHEdldEFjY2Vzc1Rva2VuQnlSZWZy",
            "ZXNoVG9rZW4SGy5TUC5TZXJ2aWNlLlRva2VuS2V5UmVxdWVzdBofLlNQLlNl",
            "cnZpY2UuQWNjZXNzVG9rZW5SZXNwb25zZSIAElMKDkFkZEFjY2Vzc1Rva2Vu",
            "Eh4uU1AuU2VydmljZS5BY2Nlc3NUb2tlblJlcXVlc3QaHy5TUC5TZXJ2aWNl",
            "LkFjY2Vzc1Rva2VuUmVzcG9uc2UiABJSChFSZW1vdmVBY2Nlc3NUb2tlbhIa",
            "LlNQLlNlcnZpY2UuVG9rZW5JZFJlcXVlc3QaHy5TUC5TZXJ2aWNlLkFjY2Vz",
            "c1Rva2VuUmVzcG9uc2UiABJUChFHZXRSZWdpb25EYXRhTGlzdBIdLlNQLlNl",
            "cnZpY2UuUmVnaW9uRGF0YVJlcXVlc3QaHi5TUC5TZXJ2aWNlLlJlZ2lvbkxp",
            "c3RSZXNwb25zZSIAEk4KDUdldFJlZ2lvbkRhdGESGy5TUC5TZXJ2aWNlLlJl",
            "Z2lvbklEUmVxdWVzdBoeLlNQLlNlcnZpY2UuUmVnaW9uRGF0YVJlc3BvbnNl",
            "IgASUwoSR2V0Q2hpbGRSZWdpb25EYXRhEhsuU1AuU2VydmljZS5SZWdpb25J",
            "RFJlcXVlc3QaHi5TUC5TZXJ2aWNlLlJlZ2lvbkxpc3RSZXNwb25zZSIAElwK",
            "D0FkZFNob3BwaW5nQ2FydBIfLlNQLlNlcnZpY2UuU2hvcHBpbmdDYXJ0UmVx",
            "dWVzdBomLlNQLlNlcnZpY2UuU2hvcHBpbmdDYXJ0UmVzdWx0UmVzcG9uc2Ui",
            "ABJdChVHZXRNeVNob3BwaW5nQ2FydExpc3QSHC5TUC5TZXJ2aWNlLkFjY291",
            "bnRJZFJlcXVlc3QaJC5TUC5TZXJ2aWNlLlNob3BwaW5nQ2FydExpc3RSZXNw",
            "b25zZSIAEmsKHkdldE15U2hvcHBpbmdDYXJ0TGlzdEJ5T3JkZXJJZBIhLlNQ",
            "LlNlcnZpY2UuTXlTaG9wcGluZ0NhcnRSZXF1ZXN0GiQuU1AuU2VydmljZS5T",
            "aG9wcGluZ0NhcnRMaXN0UmVzcG9uc2UiABJfChZHZXRNeVNob3BwaW5nQ2Fy",
            "dENvdW50EhwuU1AuU2VydmljZS5BY2NvdW50SWRSZXF1ZXN0GiUuU1AuU2Vy",
            "dmljZS5TaG9wcGluZ0NhcnRDb3VudFJlc3BvbnNlIgASbwoaVXBkYXRlU2hv",
            "cHBpbmdDYXJ0UXVhbnRpdHkSJy5TUC5TZXJ2aWNlLlNob3BwaW5nQ2FydFF1",
            "YW50aXR5UmVxdWVzdBomLlNQLlNlcnZpY2UuU2hvcHBpbmdDYXJ0UmVzdWx0",
            "UmVzcG9uc2UiABJjChlVcGRhdGVTaG9wcGluZ0NhcnRFbmFibGVkEhwuU1Au",
            "U2VydmljZS5BY2NvdW50SWRSZXF1ZXN0GiYuU1AuU2VydmljZS5TaG9wcGlu",
            "Z0NhcnRSZXN1bHRSZXNwb25zZSIAEm0KGVVwZGF0ZVNob3BwaW5nQ2FydE9y",
            "ZGVySWQSJi5TUC5TZXJ2aWNlLlNob3BwaW5nQ2FydE9yZGVySWRSZXF1ZXN0",
            "GiYuU1AuU2VydmljZS5TaG9wcGluZ0NhcnRSZXN1bHRSZXNwb25zZSIAElsK",
            "GUdldFNlbGVjdGVkUmVnaW9uRGF0YUxpc3QSHC5TUC5TZXJ2aWNlLkFjY291",
            "bnRJZFJlcXVlc3QaHi5TUC5TZXJ2aWNlLlJlZ2lvbkxpc3RSZXNwb25zZSIA",
            "ElgKGUdldERlZmF1bHRTZWxlY3RlZEFkZHJlc3MSHC5TUC5TZXJ2aWNlLkFj",
            "Y291bnRJZFJlcXVlc3QaGy5TUC5TZXJ2aWNlLkFkZHJlc3NSZXNwb25zZSIA",
            "ElcKFkdldENoaWxkUmVnaW9uRGF0YUxpc3QSGy5TUC5TZXJ2aWNlLlJlZ2lv",
            "bklEUmVxdWVzdBoeLlNQLlNlcnZpY2UuUmVnaW9uTGlzdFJlc3BvbnNlIgAS",
            "ZQoYQWRkQWNjb3VudEF1dGhlbnRpY2F0aW9uEiQuU1AuU2VydmljZS5BZGRB",
            "dXRoZW50aWNhdGlvblJlcXVlc3QaIS5TUC5TZXJ2aWNlLkFjY291bnRSZXN1",
            "bHRSZXNwb25zZSIAEmEKG0dldFZhbGlkVmVyaWZ5Q29kZUJ5QWNjb3VudBIg",
            "LlNQLlNlcnZpY2UuR2V0VmVyaWZ5Q29kZVJlcXVlc3QaHi5TUC5TZXJ2aWNl",
            "LlZlcmlmeUNvZGVSZXNwb25zZSIAEmkKGVVwZGF0ZUF1dGhTdGF0dXNCeUFj",
            "Y291bnQSJy5TUC5TZXJ2aWNlLlVwZGF0ZUF1dGhlbnRpY2F0aW9uUmVxdWVz",
            "dBohLlNQLlNlcnZpY2UuQWNjb3VudFJlc3VsdFJlc3BvbnNlIgASUwoNQWRk",
            "QXNzb2NpYXRvchIgLlNQLlNlcnZpY2UuQWRkQXNzb2NpYXRvclJlcXVlc3Qa",
            "Hi5TUC5TZXJ2aWNlLkFzc29jaWF0b3JSZXNwb25zZSIAEmgKFlVwZGF0ZUFz",
            "c29jaWF0b3JTdGF0dXMSKS5TUC5TZXJ2aWNlLlVwZGF0ZUFzc29jaWF0b3JT",
            "dGF0dXNSZXF1ZXN0GiEuU1AuU2VydmljZS5BY2NvdW50UmVzdWx0UmVzcG9u",
            "c2UiABJeChhHZXRBc3NvY2lhdG9yQnlBY2NvdW50SWQSHC5TUC5TZXJ2aWNl",
            "LkFjY291bnRJZFJlcXVlc3QaIi5TUC5TZXJ2aWNlLkFzc29jaWF0b3JMaXN0",
            "UmVzcG9uc2UiABJWChFHZXRBc3NvY2lhdG9yQnlJZBIfLlNQLlNlcnZpY2Uu",
            "QXNzb2NpYXRvcklkUmVxdWVzdBoeLlNQLlNlcnZpY2UuQXNzb2NpYXRvclJl",
            "c3BvbnNlIgASUgoOR2V0U3lzS2luZExpc3QSHS5TUC5TZXJ2aWNlLkdldFN5",
            "c0tpbmRSZXF1ZXN0Gh8uU1AuU2VydmljZS5TeXNLaW5kTGlzdFJlc3BvbnNl",
            "IgASWQoSR2V0QWNjb3VudEZ1bGxJbmZvEhwuU1AuU2VydmljZS5BY2NvdW50",
            "SWRSZXF1ZXN0GiMuU1AuU2VydmljZS5BY2NvdW50RnVsbEluZm9SZXNwb25z",
            "ZSIAEmAKFVVwZGF0ZUFjY291bnRGdWxsSW5mbxIiLlNQLlNlcnZpY2UuQWNj",
            "b3VudEZ1bGxJbmZvUmVxdWVzdBohLlNQLlNlcnZpY2UuQWNjb3VudFJlc3Vs",
            "dFJlc3BvbnNlIgASWwoWR2V0RGlzY291bnRCeUFjY291bnRJZBIbLlNQLlNl",
            "cnZpY2UuRGlzY291bnRSZXF1ZXN0GiIuU1AuU2VydmljZS5Bc3NvY2lhdG9y",
            "TGlzdFJlc3BvbnNlIgBiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SP.Service.CommonModelReflection.Descriptor, global::SP.Service.AccountModelReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
