// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductService.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SP.Service {

  /// <summary>Holder for reflection information generated from ProductService.proto</summary>
  public static partial class ProductServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for ProductService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProductServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRQcm9kdWN0U2VydmljZS5wcm90bxIKU1AuU2VydmljZRoRQ29tbW9uTW9k",
            "ZWwucHJvdG8aElByb2R1Y3RNb2RlbC5wcm90bzLcBwoOUHJvZHVjdFNlcnZp",
            "Y2USUwoOR2V0UHJvZHVjdExpc3QSHi5TUC5TZXJ2aWNlLlByb2R1Y3RMaXN0",
            "UmVxdWVzdBofLlNQLlNlcnZpY2UuUHJvZHVjdExpc3RSZXNwb25zZSIAElQK",
            "EEdldFByb2R1Y3REZXRhaWwSHC5TUC5TZXJ2aWNlLlByb2R1Y3RJZFJlcXVl",
            "c3QaIC5TUC5TZXJ2aWNlLlByb2RjdERldGFpbFJlc3BvbnNlIgASWAoXR2V0",
            "UHJvZHVjdExpc3RCeUJyYW5kSWQSGi5TUC5TZXJ2aWNlLkJyYW5kSWRSZXF1",
            "ZXN0Gh8uU1AuU2VydmljZS5Qcm9kdWN0TGlzdFJlc3BvbnNlIgASVgoWR2V0",
            "UHJvZHVjdExpc3RCeVR5cGVJZBIZLlNQLlNlcnZpY2UuVHlwZUlkUmVxdWVz",
            "dBofLlNQLlNlcnZpY2UuUHJvZHVjdExpc3RSZXNwb25zZSIAEmAKG0dldFBy",
            "b2R1Y3RMaXN0QnlBdHRyaWJ1dGVJZBIeLlNQLlNlcnZpY2UuQXR0cmlidXRl",
            "SWRSZXF1ZXN0Gh8uU1AuU2VydmljZS5Qcm9kdWN0TGlzdFJlc3BvbnNlIgAS",
            "XwoYU2VhcmNoUHJvZHVjdEtleXdvcmRMaXN0EiAuU1AuU2VydmljZS5TZWFy",
            "Y2hQcm9kdWN0UmVxdWVzdBofLlNQLlNlcnZpY2UuUHJvZHVjdExpc3RSZXNw",
            "b25zZSIAEmgKFUdldFRpdGxlQXR0cmlidXRlTGlzdBIlLlNQLlNlcnZpY2Uu",
            "VGl0bGVBdHRyaWJ1dGVMaXN0UmVxdWVzdBomLlNQLlNlcnZpY2UuVGl0bGVB",
            "dHRyaWJ1dGVMaXN0UmVzcG9uc2UiABJNCg5HZXRBbGxTaG9wTGlzdBIbLlNQ",
            "LlNlcnZpY2UuU2hvcExpc3RSZXF1ZXN0GhwuU1AuU2VydmljZS5TaG9wTGlz",
            "dFJlc3BvbnNlIgASWwoSR2V0U2hvcFByb2R1Y3RMaXN0EiIuU1AuU2Vydmlj",
            "ZS5TaG9wUHJvZHVjdExpc3RSZXF1ZXN0Gh8uU1AuU2VydmljZS5Qcm9kdWN0",
            "TGlzdFJlc3BvbnNlIgASRAoLR2V0U2hvcEJ5SWQSGS5TUC5TZXJ2aWNlLlNo",
            "b3BJZFJlcXVlc3QaGC5TUC5TZXJ2aWNlLlNob3BSZXNwb25zZSIAEk4KD0dl",
            "dENhcm91c2VsTGlzdBIXLlNQLlNlcnZpY2UuVm9pZFJlcXVlc3QaIC5TUC5T",
            "ZXJ2aWNlLkNhcm91c2VsTGlzdFJlc3BvbnNlIgBiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SP.Service.CommonModelReflection.Descriptor, global::SP.Service.ProductModelReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
