// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountService.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SP.Service {

  /// <summary>Holder for reflection information generated from AccountService.proto</summary>
  public static partial class AccountServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for AccountService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AccountServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRBY2NvdW50U2VydmljZS5wcm90bxIKU1AuU2VydmljZRoRQ29tbW9uTW9k",
            "ZWwucHJvdG8aEkFjY291bnRNb2RlbC5wcm90bzLuKwoOQWNjb3VudFNlcnZp",
            "Y2USTwoNUmVnaXN0QWNjb3VudBIZLlNQLlNlcnZpY2UuUmVnaXN0UmVxdWVz",
            "dBohLlNQLlNlcnZpY2UuQWNjb3VudFJlc3VsdFJlc3BvbnNlIgASVgoNVXBk",
            "YXRlQWNjb3VudBIgLlNQLlNlcnZpY2UuVXBkYXRlQWNjb3VudFJlcXVlc3Qa",
            "IS5TUC5TZXJ2aWNlLkFjY291bnRSZXN1bHRSZXNwb25zZSIAEk4KDVZhbGlk",
            "YXRlTG9naW4SGC5TUC5TZXJ2aWNlLkxvZ2luUmVxdWVzdBohLlNQLlNlcnZp",
            "Y2UuQWNjb3VudFJlc3VsdFJlc3BvbnNlIgASTwoQR2V0QWNjb3VudERldGFp",
            "bBIcLlNQLlNlcnZpY2UuQWNjb3VudElkUmVxdWVzdBobLlNQLlNlcnZpY2Uu",
            "QWNjb3VudFJlc3BvbnNlIgASRwoKR2V0QWNjb3VudBIaLlNQLlNlcnZpY2Uu",
            "QWNjb3VudFJlcXVlc3QaGy5TUC5TZXJ2aWNlLkFjY291bnRSZXNwb25zZSIA",
            "ElQKEUFkZEFjY291bnRBZGRyZXNzEhouU1AuU2VydmljZS5BZGRyZXNzUmVx",
            "dWVzdBohLlNQLlNlcnZpY2UuQWNjb3VudFJlc3VsdFJlc3BvbnNlIgASVQoS",
            "RWRpdEFjY291bnRBZGRyZXNzEhouU1AuU2VydmljZS5BZGRyZXNzUmVxdWVz",
            "dBohLlNQLlNlcnZpY2UuQWNjb3VudFJlc3VsdFJlc3BvbnNlIgASXAoTVXBk",
            "YXRlQWRkcmVzc1N0YXR1cxIgLlNQLlNlcnZpY2UuQWRkcmVzc1N0YXR1c1Jl",
            "cXVlc3QaIS5TUC5TZXJ2aWNlLkFjY291bnRSZXN1bHRSZXNwb25zZSIAElgK",
            "EVVwZGF0ZUFkZHJlc3NEb3JtEh4uU1AuU2VydmljZS5BZGRyZXNzRG9ybVJl",
            "cXVlc3QaIS5TUC5TZXJ2aWNlLkFjY291bnRSZXN1bHRSZXNwb25zZSIAElEK",
            "DkdldEFkZHJlc3NMaXN0EhwuU1AuU2VydmljZS5BY2NvdW50SWRSZXF1ZXN0",
            "Gh8uU1AuU2VydmljZS5BZGRyZXNzTGlzdFJlc3BvbnNlIgASUAoKRGVsQWRk",
            "cmVzcxIdLlNQLlNlcnZpY2UuRGVsQWRkcmVzc1JlcXVlc3QaIS5TUC5TZXJ2",
            "aWNlLkFjY291bnRSZXN1bHRSZXNwb25zZSIAElAKDkdldEFjY2Vzc1Rva2Vu",
            "EhsuU1AuU2VydmljZS5Ub2tlbktleVJlcXVlc3QaHy5TUC5TZXJ2aWNlLkFj",
            "Y2Vzc1Rva2VuUmVzcG9uc2UiABJeChxHZXRBY2Nlc3NUb2tlbkJ5UmVmcmVz",
            "aFRva2VuEhsuU1AuU2VydmljZS5Ub2tlbktleVJlcXVlc3QaHy5TUC5TZXJ2",
            "aWNlLkFjY2Vzc1Rva2VuUmVzcG9uc2UiABJTCg5BZGRBY2Nlc3NUb2tlbhIe",
            "LlNQLlNlcnZpY2UuQWNjZXNzVG9rZW5SZXF1ZXN0Gh8uU1AuU2VydmljZS5B",
            "Y2Nlc3NUb2tlblJlc3BvbnNlIgASUgoRUmVtb3ZlQWNjZXNzVG9rZW4SGi5T",
            "UC5TZXJ2aWNlLlRva2VuSWRSZXF1ZXN0Gh8uU1AuU2VydmljZS5BY2Nlc3NU",
            "b2tlblJlc3BvbnNlIgASVAoRR2V0UmVnaW9uRGF0YUxpc3QSHS5TUC5TZXJ2",
            "aWNlLlJlZ2lvbkRhdGFSZXF1ZXN0Gh4uU1AuU2VydmljZS5SZWdpb25MaXN0",
            "UmVzcG9uc2UiABJOCg1HZXRSZWdpb25EYXRhEhsuU1AuU2VydmljZS5SZWdp",
            "b25JRFJlcXVlc3QaHi5TUC5TZXJ2aWNlLlJlZ2lvbkRhdGFSZXNwb25zZSIA",
            "ElYKEkdldENoaWxkUmVnaW9uRGF0YRIeLlNQLlNlcnZpY2UuQ2hpbGRSZWdp",
            "b25SZXF1ZXN0Gh4uU1AuU2VydmljZS5SZWdpb25MaXN0UmVzcG9uc2UiABJc",
            "Cg9BZGRTaG9wcGluZ0NhcnQSHy5TUC5TZXJ2aWNlLlNob3BwaW5nQ2FydFJl",
            "cXVlc3QaJi5TUC5TZXJ2aWNlLlNob3BwaW5nQ2FydFJlc3VsdFJlc3BvbnNl",
            "IgASYwoVR2V0TXlTaG9wcGluZ0NhcnRMaXN0EiIuU1AuU2VydmljZS5HZXRT",
            "aG9wcGluZ0NhcnRSZXF1ZXN0GiQuU1AuU2VydmljZS5TaG9wcGluZ0NhcnRM",
            "aXN0UmVzcG9uc2UiABJrCh5HZXRNeVNob3BwaW5nQ2FydExpc3RCeU9yZGVy",
            "SWQSIS5TUC5TZXJ2aWNlLk15U2hvcHBpbmdDYXJ0UmVxdWVzdBokLlNQLlNl",
            "cnZpY2UuU2hvcHBpbmdDYXJ0TGlzdFJlc3BvbnNlIgASXwoWR2V0TXlTaG9w",
            "cGluZ0NhcnRDb3VudBIcLlNQLlNlcnZpY2UuQWNjb3VudElkUmVxdWVzdBol",
            "LlNQLlNlcnZpY2UuU2hvcHBpbmdDYXJ0Q291bnRSZXNwb25zZSIAEm8KGlVw",
            "ZGF0ZVNob3BwaW5nQ2FydFF1YW50aXR5EicuU1AuU2VydmljZS5TaG9wcGlu",
            "Z0NhcnRRdWFudGl0eVJlcXVlc3QaJi5TUC5TZXJ2aWNlLlNob3BwaW5nQ2Fy",
            "dFJlc3VsdFJlc3BvbnNlIgASYwoZVXBkYXRlU2hvcHBpbmdDYXJ0RW5hYmxl",
            "ZBIcLlNQLlNlcnZpY2UuQWNjb3VudElkUmVxdWVzdBomLlNQLlNlcnZpY2Uu",
            "U2hvcHBpbmdDYXJ0UmVzdWx0UmVzcG9uc2UiABJtChlVcGRhdGVTaG9wcGlu",
            "Z0NhcnRPcmRlcklkEiYuU1AuU2VydmljZS5TaG9wcGluZ0NhcnRPcmRlcklk",
            "UmVxdWVzdBomLlNQLlNlcnZpY2UuU2hvcHBpbmdDYXJ0UmVzdWx0UmVzcG9u",
            "c2UiABJbChlHZXRTZWxlY3RlZFJlZ2lvbkRhdGFMaXN0EhwuU1AuU2Vydmlj",
            "ZS5BY2NvdW50SWRSZXF1ZXN0Gh4uU1AuU2VydmljZS5SZWdpb25MaXN0UmVz",
            "cG9uc2UiABJYChlHZXREZWZhdWx0U2VsZWN0ZWRBZGRyZXNzEhwuU1AuU2Vy",
            "dmljZS5BY2NvdW50SWRSZXF1ZXN0GhsuU1AuU2VydmljZS5BZGRyZXNzUmVz",
            "cG9uc2UiABJaChZHZXRDaGlsZFJlZ2lvbkRhdGFMaXN0Eh4uU1AuU2Vydmlj",
            "ZS5DaGlsZFJlZ2lvblJlcXVlc3QaHi5TUC5TZXJ2aWNlLlJlZ2lvbkxpc3RS",
            "ZXNwb25zZSIAEmUKGEFkZEFjY291bnRBdXRoZW50aWNhdGlvbhIkLlNQLlNl",
            "cnZpY2UuQWRkQXV0aGVudGljYXRpb25SZXF1ZXN0GiEuU1AuU2VydmljZS5B",
            "Y2NvdW50UmVzdWx0UmVzcG9uc2UiABJhChtHZXRWYWxpZFZlcmlmeUNvZGVC",
            "eUFjY291bnQSIC5TUC5TZXJ2aWNlLkdldFZlcmlmeUNvZGVSZXF1ZXN0Gh4u",
            "U1AuU2VydmljZS5WZXJpZnlDb2RlUmVzcG9uc2UiABJpChlVcGRhdGVBdXRo",
            "U3RhdHVzQnlBY2NvdW50EicuU1AuU2VydmljZS5VcGRhdGVBdXRoZW50aWNh",
            "dGlvblJlcXVlc3QaIS5TUC5TZXJ2aWNlLkFjY291bnRSZXN1bHRSZXNwb25z",
            "ZSIAElMKDUFkZEFzc29jaWF0b3ISIC5TUC5TZXJ2aWNlLkFkZEFzc29jaWF0",
            "b3JSZXF1ZXN0Gh4uU1AuU2VydmljZS5Bc3NvY2lhdG9yUmVzcG9uc2UiABJo",
            "ChZVcGRhdGVBc3NvY2lhdG9yU3RhdHVzEikuU1AuU2VydmljZS5VcGRhdGVB",
            "c3NvY2lhdG9yU3RhdHVzUmVxdWVzdBohLlNQLlNlcnZpY2UuQWNjb3VudFJl",
            "c3VsdFJlc3BvbnNlIgASXgoYR2V0QXNzb2NpYXRvckJ5QWNjb3VudElkEhwu",
            "U1AuU2VydmljZS5BY2NvdW50SWRSZXF1ZXN0GiIuU1AuU2VydmljZS5Bc3Nv",
            "Y2lhdG9yTGlzdFJlc3BvbnNlIgASVgoRR2V0QXNzb2NpYXRvckJ5SWQSHy5T",
            "UC5TZXJ2aWNlLkFzc29jaWF0b3JJZFJlcXVlc3QaHi5TUC5TZXJ2aWNlLkFz",
            "c29jaWF0b3JSZXNwb25zZSIAEloKE0dldEFzc29jaWF0b3JCeUNvZGUSIS5T",
            "UC5TZXJ2aWNlLkFzc29jaWF0b3JDb2RlUmVxdWVzdBoeLlNQLlNlcnZpY2Uu",
            "QXNzb2NpYXRvclJlc3BvbnNlIgASUgoOR2V0U3lzS2luZExpc3QSHS5TUC5T",
            "ZXJ2aWNlLkdldFN5c0tpbmRSZXF1ZXN0Gh8uU1AuU2VydmljZS5TeXNLaW5k",
            "TGlzdFJlc3BvbnNlIgASWAoVR2V0QWNjb3VudENvdXBvbnNMaXN0EhwuU1Au",
            "U2VydmljZS5BY2NvdW50SWRSZXF1ZXN0Gh8uU1AuU2VydmljZS5Db3Vwb25z",
            "TGlzdFJlc3BvbnNlIgASWQoSR2V0QWNjb3VudEZ1bGxJbmZvEhwuU1AuU2Vy",
            "dmljZS5BY2NvdW50SWRSZXF1ZXN0GiMuU1AuU2VydmljZS5BY2NvdW50RnVs",
            "bEluZm9SZXNwb25zZSIAEmAKFVVwZGF0ZUFjY291bnRGdWxsSW5mbxIiLlNQ",
            "LlNlcnZpY2UuQWNjb3VudEZ1bGxJbmZvUmVxdWVzdBohLlNQLlNlcnZpY2Uu",
            "QWNjb3VudFJlc3VsdFJlc3BvbnNlIgASWwoWR2V0RGlzY291bnRCeUFjY291",
            "bnRJZBIbLlNQLlNlcnZpY2UuRGlzY291bnRSZXF1ZXN0GiIuU1AuU2Vydmlj",
            "ZS5Bc3NvY2lhdG9yTGlzdFJlc3BvbnNlIgASWQoQU2V0QWNjb3VudFBheVB3",
            "ZBIgLlNQLlNlcnZpY2UuQWNjb3VudFBheVB3ZFJlcXVlc3QaIS5TUC5TZXJ2",
            "aWNlLkFjY291bnRSZXN1bHRSZXNwb25zZSIAElwKE1VwZGF0ZUFjY291bnRQ",
            "YXlQd2QSIC5TUC5TZXJ2aWNlLkFjY291bnRQYXlQd2RSZXF1ZXN0GiEuU1Au",
            "U2VydmljZS5BY2NvdW50UmVzdWx0UmVzcG9uc2UiABJeChVVcGRhdGVBY2Nv",
            "dW50TG9naW5Qd2QSIC5TUC5TZXJ2aWNlLkFjY291bnRQYXlQd2RSZXF1ZXN0",
            "GiEuU1AuU2VydmljZS5BY2NvdW50UmVzdWx0UmVzcG9uc2UiABJcChNVcGRh",
            "dGVBY2NvdW50TW9iaWxlEiAuU1AuU2VydmljZS5BY2NvdW50TW9iaWxlUmVx",
            "dWVzdBohLlNQLlNlcnZpY2UuQWNjb3VudFJlc3VsdFJlc3BvbnNlIgASVwoQ",
            "QmluZE90aGVyQWNjb3VudBIeLlNQLlNlcnZpY2UuQmluZ0FjY291bnRSZXF1",
            "ZXN0GiEuU1AuU2VydmljZS5BY2NvdW50UmVzdWx0UmVzcG9uc2UiABJaChJD",
            "cmVhdGVPdGhlckFjY291bnQSHy5TUC5TZXJ2aWNlLk90aGVyQWNjb3VudFJl",
            "cXVlc3QaIS5TUC5TZXJ2aWNlLkFjY291bnRSZXN1bHRSZXNwb25zZSIAElQK",
            "D0dldE90aGVyQWNjb3VudBIiLlNQLlNlcnZpY2UuR2V0T3RoZXJBY2NvdW50",
            "UmVxdWVzdBobLlNQLlNlcnZpY2UuQWNjb3VudFJlc3BvbnNlIgASWAoTVXBk",
            "YXRlQWNjb3VudElESW5mbxIcLlNQLlNlcnZpY2UuQWNjb3VudElEUmVxdWVz",
            "dBohLlNQLlNlcnZpY2UuQWNjb3VudFJlc3VsdFJlc3BvbnNlIgASVAoMQXBw",
            "bHlQYXJ0bmVyEh8uU1AuU2VydmljZS5BcHBseVBhcnRuZXJSZXF1ZXN0GiEu",
            "U1AuU2VydmljZS5BY2NvdW50UmVzdWx0UmVzcG9uc2UiABJQCgpCYWxhbmNl",
            "UGF5Eh0uU1AuU2VydmljZS5CYWxhbmNlUGF5UmVxdWVzdBohLlNQLlNlcnZp",
            "Y2UuQWNjb3VudFJlc3VsdFJlc3BvbnNlIgASTQoMR2V0VHJhZGVMaXN0Ehwu",
            "U1AuU2VydmljZS5UcmFkZUxpc3RSZXF1ZXN0Gh0uU1AuU2VydmljZS5UcmFk",
            "ZUxpc3RSZXNwb25zZSIAElMKEUdldFRyYWRlTGlzdENvdW50EhwuU1AuU2Vy",
            "dmljZS5BY2NvdW50SURSZXF1ZXN0Gh4uU1AuU2VydmljZS5UcmFkZVRvdGFs",
            "UmVzcG9uc2UiABJbChZVcGRhdGVBY2NvdW50V3hVbmlvbklkEhwuU1AuU2Vy",
            "dmljZS5XeFVuaW9uSWRSZXF1ZXN0GiEuU1AuU2VydmljZS5BY2NvdW50UmVz",
            "dWx0UmVzcG9uc2UiABJoChZDcmVhdGVBY2NvdW50V3hVbmlvbklkEikuU1Au",
            "U2VydmljZS5DcmVhdGVBY2NvdW50V3hVbmlvbklkUmVxdWVzdBohLlNQLlNl",
            "cnZpY2UuQWNjb3VudFJlc3VsdFJlc3BvbnNlIgASUgoOQ3JlYXRlV3hPcGVu",
            "SWQSGy5TUC5TZXJ2aWNlLld4T3BlbklkUmVxdWVzdBohLlNQLlNlcnZpY2Uu",
            "QWNjb3VudFJlc3VsdFJlc3BvbnNlIgASSAoJQWRkQ291cG9uEhwuU1AuU2Vy",
            "dmljZS5BZGRDb3Vwb25SZXF1ZXN0GhsuU1AuU2VydmljZS5Db3Vwb25zUmVz",
            "cG9uc2UiABJUCgxVcGRhdGVDb3Vwb24SHy5TUC5TZXJ2aWNlLlVwZGF0ZUNv",
            "dXBvblJlcXVlc3QaIS5TUC5TZXJ2aWNlLkFjY291bnRSZXN1bHRSZXNwb25z",
            "ZSIAEk8KD0dldENvdXBvbkJ5Q29kZRIdLlNQLlNlcnZpY2UuQ291cG9uQ29k",
            "ZVJlcXVlc3QaGy5TUC5TZXJ2aWNlLkNvdXBvbnNSZXNwb25zZSIAEksKDUdl",
            "dENvdXBvbkJ5SWQSGy5TUC5TZXJ2aWNlLkNvdXBvbklkUmVxdWVzdBobLlNQ",
            "LlNlcnZpY2UuQ291cG9uc1Jlc3BvbnNlIgASUgoTR2V0QWNjb3VudEJ5VW5p",
            "b25JZBIcLlNQLlNlcnZpY2UuV3hVbmlvbklkUmVxdWVzdBobLlNQLlNlcnZp",
            "Y2UuQWNjb3VudFJlc3BvbnNlIgASWAoXR2V0QWNjb3VudEJ5TW9iaWxlUGhv",
            "bmUSHi5TUC5TZXJ2aWNlLk1vYmlsZVBob25lUmVxdWVzdBobLlNQLlNlcnZp",
            "Y2UuQWNjb3VudFJlc3BvbnNlIgBiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SP.Service.CommonModelReflection.Descriptor, global::SP.Service.AccountModelReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
