// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountService.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SP.Service {

  /// <summary>Holder for reflection information generated from AccountService.proto</summary>
  public static partial class AccountServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for AccountService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AccountServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRBY2NvdW50U2VydmljZS5wcm90bxIKU1AuU2VydmljZRoRQ29tbW9uTW9k",
            "ZWwucHJvdG8aEkFjY291bnRNb2RlbC5wcm90bzK1IgoOQWNjb3VudFNlcnZp",
            "Y2USTwoNUmVnaXN0QWNjb3VudBIZLlNQLlNlcnZpY2UuUmVnaXN0UmVxdWVz",
            "dBohLlNQLlNlcnZpY2UuQWNjb3VudFJlc3VsdFJlc3BvbnNlIgASVgoNVXBk",
            "YXRlQWNjb3VudBIgLlNQLlNlcnZpY2UuVXBkYXRlQWNjb3VudFJlcXVlc3Qa",
            "IS5TUC5TZXJ2aWNlLkFjY291bnRSZXN1bHRSZXNwb25zZSIAEk4KDVZhbGlk",
            "YXRlTG9naW4SGC5TUC5TZXJ2aWNlLkxvZ2luUmVxdWVzdBohLlNQLlNlcnZp",
            "Y2UuQWNjb3VudFJlc3VsdFJlc3BvbnNlIgASTwoQR2V0QWNjb3VudERldGFp",
            "bBIcLlNQLlNlcnZpY2UuQWNjb3VudElkUmVxdWVzdBobLlNQLlNlcnZpY2Uu",
            "QWNjb3VudFJlc3BvbnNlIgASRwoKR2V0QWNjb3VudBIaLlNQLlNlcnZpY2Uu",
            "QWNjb3VudFJlcXVlc3QaGy5TUC5TZXJ2aWNlLkFjY291bnRSZXNwb25zZSIA",
            "ElQKEUFkZEFjY291bnRBZGRyZXNzEhouU1AuU2VydmljZS5BZGRyZXNzUmVx",
            "dWVzdBohLlNQLlNlcnZpY2UuQWNjb3VudFJlc3VsdFJlc3BvbnNlIgASVQoS",
            "RWRpdEFjY291bnRBZGRyZXNzEhouU1AuU2VydmljZS5BZGRyZXNzUmVxdWVz",
            "dBohLlNQLlNlcnZpY2UuQWNjb3VudFJlc3VsdFJlc3BvbnNlIgASXAoTVXBk",
            "YXRlQWRkcmVzc1N0YXR1cxIgLlNQLlNlcnZpY2UuQWRkcmVzc1N0YXR1c1Jl",
            "cXVlc3QaIS5TUC5TZXJ2aWNlLkFjY291bnRSZXN1bHRSZXNwb25zZSIAElgK",
            "EVVwZGF0ZUFkZHJlc3NEb3JtEh4uU1AuU2VydmljZS5BZGRyZXNzRG9ybVJl",
            "cXVlc3QaIS5TUC5TZXJ2aWNlLkFjY291bnRSZXN1bHRSZXNwb25zZSIAElEK",
            "DkdldEFkZHJlc3NMaXN0EhwuU1AuU2VydmljZS5BY2NvdW50SWRSZXF1ZXN0",
            "Gh8uU1AuU2VydmljZS5BZGRyZXNzTGlzdFJlc3BvbnNlIgASUAoKRGVsQWRk",
            "cmVzcxIdLlNQLlNlcnZpY2UuRGVsQWRkcmVzc1JlcXVlc3QaIS5TUC5TZXJ2",
            "aWNlLkFjY291bnRSZXN1bHRSZXNwb25zZSIAElAKDkdldEFjY2Vzc1Rva2Vu",
            "EhsuU1AuU2VydmljZS5Ub2tlbktleVJlcXVlc3QaHy5TUC5TZXJ2aWNlLkFj",
            "Y2Vzc1Rva2VuUmVzcG9uc2UiABJeChxHZXRBY2Nlc3NUb2tlbkJ5UmVmcmVz",
            "aFRva2VuEhsuU1AuU2VydmljZS5Ub2tlbktleVJlcXVlc3QaHy5TUC5TZXJ2",
            "aWNlLkFjY2Vzc1Rva2VuUmVzcG9uc2UiABJTCg5BZGRBY2Nlc3NUb2tlbhIe",
            "LlNQLlNlcnZpY2UuQWNjZXNzVG9rZW5SZXF1ZXN0Gh8uU1AuU2VydmljZS5B",
            "Y2Nlc3NUb2tlblJlc3BvbnNlIgASUgoRUmVtb3ZlQWNjZXNzVG9rZW4SGi5T",
            "UC5TZXJ2aWNlLlRva2VuSWRSZXF1ZXN0Gh8uU1AuU2VydmljZS5BY2Nlc3NU",
            "b2tlblJlc3BvbnNlIgASVAoRR2V0UmVnaW9uRGF0YUxpc3QSHS5TUC5TZXJ2",
            "aWNlLlJlZ2lvbkRhdGFSZXF1ZXN0Gh4uU1AuU2VydmljZS5SZWdpb25MaXN0",
            "UmVzcG9uc2UiABJOCg1HZXRSZWdpb25EYXRhEhsuU1AuU2VydmljZS5SZWdp",
            "b25JRFJlcXVlc3QaHi5TUC5TZXJ2aWNlLlJlZ2lvbkRhdGFSZXNwb25zZSIA",
            "ElMKEkdldENoaWxkUmVnaW9uRGF0YRIbLlNQLlNlcnZpY2UuUmVnaW9uSURS",
            "ZXF1ZXN0Gh4uU1AuU2VydmljZS5SZWdpb25MaXN0UmVzcG9uc2UiABJcCg9B",
            "ZGRTaG9wcGluZ0NhcnQSHy5TUC5TZXJ2aWNlLlNob3BwaW5nQ2FydFJlcXVl",
            "c3QaJi5TUC5TZXJ2aWNlLlNob3BwaW5nQ2FydFJlc3VsdFJlc3BvbnNlIgAS",
            "YwoVR2V0TXlTaG9wcGluZ0NhcnRMaXN0EiIuU1AuU2VydmljZS5HZXRTaG9w",
            "cGluZ0NhcnRSZXF1ZXN0GiQuU1AuU2VydmljZS5TaG9wcGluZ0NhcnRMaXN0",
            "UmVzcG9uc2UiABJrCh5HZXRNeVNob3BwaW5nQ2FydExpc3RCeU9yZGVySWQS",
            "IS5TUC5TZXJ2aWNlLk15U2hvcHBpbmdDYXJ0UmVxdWVzdBokLlNQLlNlcnZp",
            "Y2UuU2hvcHBpbmdDYXJ0TGlzdFJlc3BvbnNlIgASXwoWR2V0TXlTaG9wcGlu",
            "Z0NhcnRDb3VudBIcLlNQLlNlcnZpY2UuQWNjb3VudElkUmVxdWVzdBolLlNQ",
            "LlNlcnZpY2UuU2hvcHBpbmdDYXJ0Q291bnRSZXNwb25zZSIAEm8KGlVwZGF0",
            "ZVNob3BwaW5nQ2FydFF1YW50aXR5EicuU1AuU2VydmljZS5TaG9wcGluZ0Nh",
            "cnRRdWFudGl0eVJlcXVlc3QaJi5TUC5TZXJ2aWNlLlNob3BwaW5nQ2FydFJl",
            "c3VsdFJlc3BvbnNlIgASYwoZVXBkYXRlU2hvcHBpbmdDYXJ0RW5hYmxlZBIc",
            "LlNQLlNlcnZpY2UuQWNjb3VudElkUmVxdWVzdBomLlNQLlNlcnZpY2UuU2hv",
            "cHBpbmdDYXJ0UmVzdWx0UmVzcG9uc2UiABJtChlVcGRhdGVTaG9wcGluZ0Nh",
            "cnRPcmRlcklkEiYuU1AuU2VydmljZS5TaG9wcGluZ0NhcnRPcmRlcklkUmVx",
            "dWVzdBomLlNQLlNlcnZpY2UuU2hvcHBpbmdDYXJ0UmVzdWx0UmVzcG9uc2Ui",
            "ABJbChlHZXRTZWxlY3RlZFJlZ2lvbkRhdGFMaXN0EhwuU1AuU2VydmljZS5B",
            "Y2NvdW50SWRSZXF1ZXN0Gh4uU1AuU2VydmljZS5SZWdpb25MaXN0UmVzcG9u",
            "c2UiABJYChlHZXREZWZhdWx0U2VsZWN0ZWRBZGRyZXNzEhwuU1AuU2Vydmlj",
            "ZS5BY2NvdW50SWRSZXF1ZXN0GhsuU1AuU2VydmljZS5BZGRyZXNzUmVzcG9u",
            "c2UiABJXChZHZXRDaGlsZFJlZ2lvbkRhdGFMaXN0EhsuU1AuU2VydmljZS5S",
            "ZWdpb25JRFJlcXVlc3QaHi5TUC5TZXJ2aWNlLlJlZ2lvbkxpc3RSZXNwb25z",
            "ZSIAEmUKGEFkZEFjY291bnRBdXRoZW50aWNhdGlvbhIkLlNQLlNlcnZpY2Uu",
            "QWRkQXV0aGVudGljYXRpb25SZXF1ZXN0GiEuU1AuU2VydmljZS5BY2NvdW50",
            "UmVzdWx0UmVzcG9uc2UiABJhChtHZXRWYWxpZFZlcmlmeUNvZGVCeUFjY291",
            "bnQSIC5TUC5TZXJ2aWNlLkdldFZlcmlmeUNvZGVSZXF1ZXN0Gh4uU1AuU2Vy",
            "dmljZS5WZXJpZnlDb2RlUmVzcG9uc2UiABJpChlVcGRhdGVBdXRoU3RhdHVz",
            "QnlBY2NvdW50EicuU1AuU2VydmljZS5VcGRhdGVBdXRoZW50aWNhdGlvblJl",
            "cXVlc3QaIS5TUC5TZXJ2aWNlLkFjY291bnRSZXN1bHRSZXNwb25zZSIAElMK",
            "DUFkZEFzc29jaWF0b3ISIC5TUC5TZXJ2aWNlLkFkZEFzc29jaWF0b3JSZXF1",
            "ZXN0Gh4uU1AuU2VydmljZS5Bc3NvY2lhdG9yUmVzcG9uc2UiABJoChZVcGRh",
            "dGVBc3NvY2lhdG9yU3RhdHVzEikuU1AuU2VydmljZS5VcGRhdGVBc3NvY2lh",
            "dG9yU3RhdHVzUmVxdWVzdBohLlNQLlNlcnZpY2UuQWNjb3VudFJlc3VsdFJl",
            "c3BvbnNlIgASXgoYR2V0QXNzb2NpYXRvckJ5QWNjb3VudElkEhwuU1AuU2Vy",
            "dmljZS5BY2NvdW50SWRSZXF1ZXN0GiIuU1AuU2VydmljZS5Bc3NvY2lhdG9y",
            "TGlzdFJlc3BvbnNlIgASVgoRR2V0QXNzb2NpYXRvckJ5SWQSHy5TUC5TZXJ2",
            "aWNlLkFzc29jaWF0b3JJZFJlcXVlc3QaHi5TUC5TZXJ2aWNlLkFzc29jaWF0",
            "b3JSZXNwb25zZSIAElIKDkdldFN5c0tpbmRMaXN0Eh0uU1AuU2VydmljZS5H",
            "ZXRTeXNLaW5kUmVxdWVzdBofLlNQLlNlcnZpY2UuU3lzS2luZExpc3RSZXNw",
            "b25zZSIAElkKEkdldEFjY291bnRGdWxsSW5mbxIcLlNQLlNlcnZpY2UuQWNj",
            "b3VudElkUmVxdWVzdBojLlNQLlNlcnZpY2UuQWNjb3VudEZ1bGxJbmZvUmVz",
            "cG9uc2UiABJgChVVcGRhdGVBY2NvdW50RnVsbEluZm8SIi5TUC5TZXJ2aWNl",
            "LkFjY291bnRGdWxsSW5mb1JlcXVlc3QaIS5TUC5TZXJ2aWNlLkFjY291bnRS",
            "ZXN1bHRSZXNwb25zZSIAElsKFkdldERpc2NvdW50QnlBY2NvdW50SWQSGy5T",
            "UC5TZXJ2aWNlLkRpc2NvdW50UmVxdWVzdBoiLlNQLlNlcnZpY2UuQXNzb2Np",
            "YXRvckxpc3RSZXNwb25zZSIAElkKEFNldEFjY291bnRQYXlQd2QSIC5TUC5T",
            "ZXJ2aWNlLkFjY291bnRQYXlQd2RSZXF1ZXN0GiEuU1AuU2VydmljZS5BY2Nv",
            "dW50UmVzdWx0UmVzcG9uc2UiABJcChNVcGRhdGVBY2NvdW50UGF5UHdkEiAu",
            "U1AuU2VydmljZS5BY2NvdW50UGF5UHdkUmVxdWVzdBohLlNQLlNlcnZpY2Uu",
            "QWNjb3VudFJlc3VsdFJlc3BvbnNlIgASXgoVVXBkYXRlQWNjb3VudExvZ2lu",
            "UHdkEiAuU1AuU2VydmljZS5BY2NvdW50UGF5UHdkUmVxdWVzdBohLlNQLlNl",
            "cnZpY2UuQWNjb3VudFJlc3VsdFJlc3BvbnNlIgASXAoTVXBkYXRlQWNjb3Vu",
            "dE1vYmlsZRIgLlNQLlNlcnZpY2UuQWNjb3VudE1vYmlsZVJlcXVlc3QaIS5T",
            "UC5TZXJ2aWNlLkFjY291bnRSZXN1bHRSZXNwb25zZSIAElcKEEJpbmRPdGhl",
            "ckFjY291bnQSHi5TUC5TZXJ2aWNlLkJpbmdBY2NvdW50UmVxdWVzdBohLlNQ",
            "LlNlcnZpY2UuQWNjb3VudFJlc3VsdFJlc3BvbnNlIgASWgoSQ3JlYXRlT3Ro",
            "ZXJBY2NvdW50Eh8uU1AuU2VydmljZS5PdGhlckFjY291bnRSZXF1ZXN0GiEu",
            "U1AuU2VydmljZS5BY2NvdW50UmVzdWx0UmVzcG9uc2UiABJUCg9HZXRPdGhl",
            "ckFjY291bnQSIi5TUC5TZXJ2aWNlLkdldE90aGVyQWNjb3VudFJlcXVlc3Qa",
            "Gy5TUC5TZXJ2aWNlLkFjY291bnRSZXNwb25zZSIAElgKE1VwZGF0ZUFjY291",
            "bnRJREluZm8SHC5TUC5TZXJ2aWNlLkFjY291bnRJRFJlcXVlc3QaIS5TUC5T",
            "ZXJ2aWNlLkFjY291bnRSZXN1bHRSZXNwb25zZSIAElQKDEFwcGx5UGFydG5l",
            "chIfLlNQLlNlcnZpY2UuQXBwbHlQYXJ0bmVyUmVxdWVzdBohLlNQLlNlcnZp",
            "Y2UuQWNjb3VudFJlc3VsdFJlc3BvbnNlIgBiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SP.Service.CommonModelReflection.Descriptor, global::SP.Service.AccountModelReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
