// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RepeatedTokenService.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SP.Service {

  /// <summary>Holder for reflection information generated from RepeatedTokenService.proto</summary>
  public static partial class RepeatedTokenServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for RepeatedTokenService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RepeatedTokenServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpSZXBlYXRlZFRva2VuU2VydmljZS5wcm90bxIKU1AuU2VydmljZRoRQ29t",
            "bW9uTW9kZWwucHJvdG8aGFJlcGVhdGVkVG9rZW5Nb2RlbC5wcm90bzK/AgoU",
            "UmVwZWF0ZWRUb2tlblNlcnZpY2USXAoQR2V0UmVwZWF0ZWRUb2tlbhIjLlNQ",
            "LlNlcnZpY2UuUmVwZWF0ZWRUb2tlbktleVJlcXVlc3QaIS5TUC5TZXJ2aWNl",
            "LlJlcGVhdGVkVG9rZW5SZXNwb25zZSIAEloKFUdlbmVyYXRlUmVwZWF0ZWRU",
            "b2tlbhIcLlNQLlNlcnZpY2UuQWNjb3VudElkUmVxdWVzdBohLlNQLlNlcnZp",
            "Y2UuUmVwZWF0ZWRUb2tlblJlc3BvbnNlIgASbQobVXBkYXRlUmVwZWF0ZWRU",
            "b2tlbkRpc2FibGVkEiMuU1AuU2VydmljZS5SZXBlYXRlZFRva2VuS2V5UmVx",
            "dWVzdBonLlNQLlNlcnZpY2UuUmVwZWF0ZWRUb2tlblJlc3VsdFJlc3BvbnNl",
            "IgBiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SP.Service.CommonModelReflection.Descriptor, global::SP.Service.RepeatedTokenModelReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
