// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RepeatedTokenService.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SP.Service {

  /// <summary>Holder for reflection information generated from RepeatedTokenService.proto</summary>
  public static partial class RepeatedTokenServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for RepeatedTokenService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RepeatedTokenServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpSZXBlYXRlZFRva2VuU2VydmljZS5wcm90bxIKU1AuU2VydmljZRoYUmVw",
            "ZWF0ZWRUb2tlbk1vZGVsLnByb3RvMrQCChRSZXBlYXRlZFRva2VuU2Vydmlj",
            "ZRJUChBHZXRSZXBlYXRlZFRva2VuEhsuU1AuU2VydmljZS5Ub2tlbktleVJl",
            "cXVlc3QaIS5TUC5TZXJ2aWNlLlJlcGVhdGVkVG9rZW5SZXNwb25zZSIAEl8K",
            "EEFkZFJlcGVhdGVkVG9rZW4SIC5TUC5TZXJ2aWNlLlJlcGVhdGVkVG9rZW5S",
            "ZXF1ZXN0GicuU1AuU2VydmljZS5SZXBlYXRlZFRva2VuUmVzdWx0UmVzcG9u",
            "c2UiABJlChtVcGRhdGVSZXBlYXRlZFRva2VuRGlzYWJsZWQSGy5TUC5TZXJ2",
            "aWNlLlRva2VuS2V5UmVxdWVzdBonLlNQLlNlcnZpY2UuUmVwZWF0ZWRUb2tl",
            "blJlc3VsdFJlc3BvbnNlIgBiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SP.Service.RepeatedTokenModelReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
