//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OAuth2_Access_Token
    {
        public int AutoId { get; set; }
        public string AccessToken { get; set; }
        public string AccountID { get; set; }
        public string AppID { get; set; }
        public string ProjectID { get; set; }
        public Nullable<System.DateTime> AccessTokenExpires { get; set; }
        public string RefreshToken { get; set; }
        public Nullable<System.DateTime> RefreshTokenExpires { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
