//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP_AccountInfo
    {
        public int Id { get; set; }
        public string AccountId { get; set; }
        public string Avatar { get; set; }
        public string Fullname { get; set; }
        public byte UserType { get; set; }
        public byte Gender { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string IM_QQ { get; set; }
        public string WeiXin { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string PayPassWord { get; set; }
    }
}
