//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP_Orders
    {
        public int Id { get; set; }
        public string OrderId { get; set; }
        public string Remark { get; set; }
        public int OrderStatus { get; set; }
        public string CloseReason { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<System.DateTime> ShippingDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public string AccountId { get; set; }
        public Nullable<System.DateTime> ShipToDate { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public decimal Amount { get; set; }
        public string Meta_Keywords { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string OrderCode { get; set; }
        public Nullable<decimal> VIPAmount { get; set; }
        public Nullable<int> AddressId { get; set; }
        public string OrderAddress { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<bool> IsVip { get; set; }
        public Nullable<bool> IsWxPay { get; set; }
        public Nullable<bool> IsAliPay { get; set; }
        public string ShiperId { get; set; }
        public int OrderType { get; set; }
        public Nullable<int> RegionId { get; set; }
    }
}
