//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP_Products
    {
        public int Id { get; set; }
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public string ShortDescription { get; set; }
        public string Unit { get; set; }
        public string Description { get; set; }
        public string Meta_Keywords { get; set; }
        public Nullable<int> SaleStatus { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<int> DisplaySequence { get; set; }
        public Nullable<decimal> MarketPrice { get; set; }
        public Nullable<int> BrandId { get; set; }
        public string SuppliersId { get; set; }
        public Nullable<long> TypeId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<long> LastOperater { get; set; }
        public Nullable<decimal> VIPPrice { get; set; }
        public Nullable<long> SecondTypeId { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
    }
}
