//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP_SuppliersProduct
    {
        public int Id { get; set; }
        public int SuppliersId { get; set; }
        public string ProductId { get; set; }
        public decimal PurchasePrice { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> AlertStock { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
