//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP_SysKind
    {
        public string KindId { get; set; }
        public int Kind { get; set; }
        public int Quantity { get; set; }
        public int Unit { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public decimal DiscountValue { get; set; }
    }
}
