//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP_Shop
    {
        public int Id { get; set; }
        public string ShopName { get; set; }
        public string OwnerId { get; set; }
        public Nullable<int> DisplaySequence { get; set; }
        public string MetaKeywords { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public Nullable<int> ShopType { get; set; }
        public string ShopLogo { get; set; }
    }
}
