//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP_Trade
    {
        public int Id { get; set; }
        public string AccountId { get; set; }
        public string TradeId { get; set; }
        public string CartId { get; set; }
        public int Subject { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<int> ShipOrderId { get; set; }
    }
}
