//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP_UserShipping
    {
        public int ShippingId { get; set; }
        public int AddressId { get; set; }
        public string AccountId { get; set; }
        public string Address { get; set; }
        public string TelPhone { get; set; }
        public string CellPhone { get; set; }
        public string EmailAddress { get; set; }
        public string RealName { get; set; }
        public string QQ { get; set; }
        public string WeChat { get; set; }
    }
}
