// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockService.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SP.Service {

  /// <summary>Holder for reflection information generated from StockService.proto</summary>
  public static partial class StockServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for StockService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StockServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJTdG9ja1NlcnZpY2UucHJvdG8SClNQLlNlcnZpY2UaEFN0b2NrTW9kZWwu",
            "cHJvdG8yqwUKDFN0b2NrU2VydmljZRJQCg1HZXRQcm9kdWN0U2t1Eh0uU1Au",
            "U2VydmljZS5Qcm9kdWN0U2t1UmVxdWVzdBoeLlNQLlNlcnZpY2UuUHJvZHVj",
            "dFNrdVJlc3BvbnNlIgASXgoUR2V0QWNjb3VudFByb2R1Y3RTa3USJC5TUC5T",
            "ZXJ2aWNlLkFjY291bnRQcm9kdWN0U2t1UmVxdWVzdBoeLlNQLlNlcnZpY2Uu",
            "UHJvZHVjdFNrdVJlc3BvbnNlIgASVgoSRGVjcmVhc2VQcm9kdWN0U2t1Eh8u",
            "U1AuU2VydmljZS5PcGVyYXRpb25Ta3VSZXF1ZXN0Gh0uU1AuU2VydmljZS5T",
            "a3VTdGF0dXNSZXNwb25zZSIAElIKDlJlZG9Qcm9kdWN0U2t1Eh8uU1AuU2Vy",
            "dmljZS5PcGVyYXRpb25Ta3VSZXF1ZXN0Gh0uU1AuU2VydmljZS5Ta3VTdGF0",
            "dXNSZXNwb25zZSIAEk4KEEFkZEludlByb2R1Y3RTa3USGS5TUC5TZXJ2aWNl",
            "LkludlNrdVJlcXVlc3QaHS5TUC5TZXJ2aWNlLlNrdVN0YXR1c1Jlc3BvbnNl",
            "IgASTgoQRGVsSW52UHJvZHVjdFNrdRIZLlNQLlNlcnZpY2UuSW52U2t1UmVx",
            "dWVzdBodLlNQLlNlcnZpY2UuU2t1U3RhdHVzUmVzcG9uc2UiABJPChBVcGRh",
            "dGVQcm9kdWN0U2t1EhouU1AuU2VydmljZS5Ta3VMaXN0UmVxdWVzdBodLlNQ",
            "LlNlcnZpY2UuU2t1U3RhdHVzUmVzcG9uc2UiABJMCg1EZWxQcm9kdWN0U2t1",
            "EhouU1AuU2VydmljZS5Ta3VMaXN0UmVxdWVzdBodLlNQLlNlcnZpY2UuU2t1",
            "U3RhdHVzUmVzcG9uc2UiAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SP.Service.StockModelReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
